#APPLICATION
spring.application.name=${APP_NAME:fakestoreservice}
server.port=${PORT:5001}


spring.datasource.url=${DB_URL:jdbc:sqlite:/tmp/products.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${SHOT_SQL:true}

#FAKESTORE URL
fakestore_url=${FAKESTORE_API_URL:https://fakestoreapi.com}
