#APPLICATION
spring.application.name=${APP_NAME:fakestoreservice}
server.port=${PORT:5001}


spring.datasource.url=jdbc:sqlite:products.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

#FAKESTORE URL
fakestore_url=${DB_URL:https://yahyatesting-env.eba-sarnymwd.eu-north-1.elasticbeanstalk.com/products}
