spring.application.name=fakestoreservice


spring.datasource.url=jdbc:sqlite:products.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true


fakestore_url=${DB_URL:http://yahyatesting-env.eba-sarnymwd.eu-north-1.elasticbeanstalk.com/products}

server.port=5000